#!/usr/bin/env bash
# socks5-bridge.sh — publish kui per-slot internal SOCKS5 exits on the host.
#
# Slot listeners (7920+) live inside the Compose network behind auto-generated
# internal credentials, so the links from `/api/sub?format=socks5` are not
# reachable from outside. This sidecar runs sing-box on the Compose network and
# re-publishes every ready slot on the host, authenticated with the management
# credentials that the subscription links already carry. A single url-test
# entry port (default 1080) is published as well.
#
# Usage:
#   vps/socks5-bridge.sh [KUI_MANAGEMENT_PASSWORD]
#
# Env overrides: KUI_COMPOSE_DIR KUI_BASE_URL KUI_CONTAINER BRIDGE_NAME
#                BRIDGE_STATE_DIR AUTO_PORT SING_BOX_IMAGE DOCKER SKIP_VERIFY
#
# Note: the published ports are reachable by anyone who can reach the host.
# Authentication is required, but SOCKS5 handshake patterns may get the ports
# blocked by national firewalls; restrict the source ranges where possible.
set -euo pipefail

KUI_COMPOSE_DIR=${KUI_COMPOSE_DIR:-/opt/kui-local-multi-exit}
KUI_BASE_URL=${KUI_BASE_URL:-http://127.0.0.1:8080}
KUI_CONTAINER=${KUI_CONTAINER:-kui-local-multi-exit}
BRIDGE_NAME=${BRIDGE_NAME:-kui-socks5-bridge}
BRIDGE_STATE_DIR=${BRIDGE_STATE_DIR:-$HOME/kui-socks5-bridge}
AUTO_PORT=${AUTO_PORT:-1080}
SING_BOX_IMAGE=${SING_BOX_IMAGE:-ghcr.io/sagernet/sing-box:latest}

DOCKER=${DOCKER:-docker}
$DOCKER info >/dev/null 2>&1 || DOCKER="sudo docker"

MGMT_USER=${KUI_MANAGEMENT_USER:-admin}
PW=${1:-${KUI_MANAGEMENT_PASSWORD:-}}
if [ -z "$PW" ] && [ -f "$KUI_COMPOSE_DIR/.env" ]; then
  PW=$(sed -n 's/^KUI_MANAGEMENT_PASSWORD=//p' "$KUI_COMPOSE_DIR/.env" | tail -1 | tr -d '\r')
fi
[ -n "$PW" ] || { echo "FATAL: pass the management password as arg 1 or via KUI_MANAGEMENT_PASSWORD" >&2; exit 1; }

# Internal per-slot credentials generated by the kui entrypoint.
GU=$($DOCKER exec "$KUI_CONTAINER" cat /opt/kui-local/internal_proxy.json \
  | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['username']); print(d['password'])")
GU_USER=$(echo "$GU" | sed -n 1p); GU_PASS=$(echo "$GU" | sed -n 2p)
[ -n "$GU_PASS" ] || { echo "FATAL: cannot read internal proxy credentials" >&2; exit 1; }

SLOTS=$(curl -fsS --max-time 10 -u "$MGMT_USER:$PW" "$KUI_BASE_URL/api/local/exits" \
  | python3 -c "import json,sys; d=json.load(sys.stdin); print(','.join(f\"{s['id']}:{s['proxy_port']}:{s.get('country') or 'UN'}\" for s in d.get('exits',[]) if s.get('state')=='ready' and s.get('proxy_port')))")
[ -n "$SLOTS" ] || { echo "FATAL: no ready slots; check /api/local/exits first" >&2; exit 1; }
echo "[*] ready slots: $SLOTS"

mkdir -p "$BRIDGE_STATE_DIR"
python3 - "$PW" "$MGMT_USER" "$GU_USER" "$GU_PASS" "$KUI_CONTAINER" "$AUTO_PORT" "$SLOTS" > "$BRIDGE_STATE_DIR/config.json" <<'PY'
import json, sys

pw, mgmt_user, gu, gp, kui_container, auto_port, slots = sys.argv[1:8]
trips = []
for item in slots.split(","):
    sid, port, cc = item.rsplit(":", 2)
    trips.append((sid, int(port), cc))
tags = [t for t, _, _ in trips]
users = [{"username": mgmt_user, "password": pw}]
inbounds = [{"type": "mixed", "tag": "auto-in", "listen": "0.0.0.0", "listen_port": int(auto_port),
             "users": users}]
for sid, port, _ in trips:
    inbounds.append({"type": "mixed", "tag": sid, "listen": "0.0.0.0", "listen_port": port,
                     "users": users})
outbounds = [{"type": "urltest", "tag": "auto", "outbounds": tags,
              "url": "http://www.gstatic.com/generate_204", "interval": "5m", "tolerance": 150}]
outbounds += [{"type": "socks", "tag": t, "server": kui_container, "server_port": p,
               "version": "5", "username": gu, "password": gp} for t, p, _ in trips]
outbounds.append({"type": "direct", "tag": "direct"})
print(json.dumps({
    "log": {"level": "warn", "timestamp": True},
    "inbounds": inbounds,
    "outbounds": outbounds,
    "route": {"rules": [{"inbound": sid, "outbound": sid} for sid, _, _ in trips], "final": "auto"},
}, indent=2))
PY

NETWORK=$($DOCKER inspect "$KUI_CONTAINER" --format '{{range $k, $_ := .NetworkSettings.Networks}}{{$k}}{{"\n"}}{{end}}' | head -1)
[ -n "$NETWORK" ] || { echo "FATAL: cannot locate the compose network" >&2; exit 1; }
PORTRANGE=$(python3 -c "
slots='''$SLOTS'''.split(',')
ps=sorted(int(s.rsplit(':',2)[1]) for s in slots)
print(f'{ps[0]}-{ps[-1]}:{ps[0]}-{ps[-1]}')")
echo "[*] publishing $PORTRANGE + $AUTO_PORT on network $NETWORK"

$DOCKER rm -f "$BRIDGE_NAME" >/dev/null 2>&1 || true
$DOCKER run -d --name "$BRIDGE_NAME" --restart unless-stopped \
  --network "$NETWORK" -p "$AUTO_PORT:$AUTO_PORT" -p "$PORTRANGE" \
  -v "$BRIDGE_STATE_DIR/config.json:/etc/sing-box/config.json:ro" \
  "$SING_BOX_IMAGE" run -c /etc/sing-box/config.json >/dev/null
sleep 3

if [ "${SKIP_VERIFY:-0}" != "1" ]; then
  second_port=$(echo "$SLOTS" | cut -d, -f2 | cut -d: -f2)
  second_port=${second_port:-$(echo "$SLOTS" | cut -d, -f1 | cut -d: -f2)}
  echo "[*] verify per-slot port $second_port: $(curl -fsS --max-time 25 -x "socks5://$MGMT_USER:$PW@127.0.0.1:$second_port" https://api.ipify.org || echo FAIL)"
  echo "[*] verify auto port $AUTO_PORT: $(curl -fsS --max-time 25 -x "socks5://$MGMT_USER:$PW@127.0.0.1:$AUTO_PORT" https://api.ipify.org || echo FAIL)"
fi

echo "[+] done. Subscription: $KUI_BASE_URL/api/sub?user=<user>&token=<token>&format=socks5"
